### ISSUE TITLE
 CodeProject AI.Server (CPU) 2.2.4 wont install

### ISSUE THREAD

**Issue by jokerigno** [skrashevich/hassio-addons#11]
This is the error I see when trying to install the addon:

> Can't install ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.2.4: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.2.4/json: Not Found ("No such image: ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.2.4")

**Comment by skrashevich** [comment]
can't reproduce

**Comment by jokerigno** [comment]
well...for me the issue does exist. And it is present, all the time. I've no issue instead while adding double-take from your repository. Do you mind reconsider your position?

**Comment by dabibbit** [comment]
This is not the same version, but I am adding this note to indicate that someone else experienced the same error with the current add-on. 

> Failed to to call /addons/0a217ee8_ai.server/install - Can't install ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.5.1: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.5.1/json: Not Found ("No such image: ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.5.1
