### ISSUE TITLE
You must install .NET to run this application.

### ISSUE THREAD

**Issue by SmileyZomb** [skrashevich/hassio-addons#12]
I have this message when I want to launch.
How can I do ?
![ai server](https://github.com/skrashevich/hassio-addons/assets/32229508/6eed70e2-4ca3-4aff-ba2b-4d34eb283611)

**Comment by skrashevich** [comment]
try to reinstall. fixed in [666fd24](https://github.com/skrashevich/hassio-addons/commit/666fd24c255dba45149cf87ce18164b9181a2057)
