### ISSUE TITLE
Unable To Locate Double-Take (or any other addons apart from AIServer) In HA Addons

### ISSUE THREAD

**Issue by townsmcp** [skrashevich/hassio-addons#14]
@skrashevich I was running an older version of DT and thought it was about time to up update. I have removed DT 1.13.10 from HA, gone into the Addon store, performed an update and can only see the following addons:
![image](https://github.com/skrashevich/hassio-addons/assets/14061617/9b2a66c8-d5a6-41f3-a170-f93b679d12c5)
I tried removing the repo and adding it back in, doing a refresh, coming out of the Addon Store and go back in - still only seeing the  1 addon (and no Double Take). Any suggestions on how to fix this so I can install the addons again?

**Comment by skrashevich** [comment]
oops. my stupid mistake.
I've fixed it right now. just reload repository

**Comment by townsmcp** [comment]
Thanks. That worked
