### ISSUE TITLE
Update gives error

### ISSUE THREAD

**Issue by mhoogenbosch** [skrashevich/hassio-addons#16]
When hitting the update button i'm getting the following error:

`Can't install ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.3.2: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=2.3.2&fromImage=ghcr.io%2Fskrashevich%2Fhassio-addon-ai.server-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

Running the AMD64 version. On 2023.11.b3

**Comment by skrashevich** [comment]
try again now

**Comment by mhoogenbosch** [comment]
Great, thanks and works
