### ISSUE TITLE
Update to 2.3.4 results in error

### ISSUE THREAD

**Issue by mhoogenbosch** [skrashevich/hassio-addons#18]
The same error as to 2.3.2, but now for 2.3.4.

`Can't install ghcr.io/skrashevich/hassio-addon-ai.server-amd64:2.3.4: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=2.3.4&fromImage=ghcr.io%2Fskrashevich%2Fhassio-addon-ai.server-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by skrashevich** [comment]
codeproject removes 2.3.4 build for amd64 :(
I updated the addon configuration: now version 2.3.4 will be installed for arm64, and 2.3.2 for amd64 (despite the addon version). when they release version 2.3.4 for amd64 again, I will update the repository again (it will be named such as 2.3.4.1)
now just re-install addon

**Comment by mhoogenbosch** [comment]
Thanks! Same error, but apparently different cause. I'll refresh and update, and maybe the AMD version will return. Thanks!

**Comment by skrashevich** [comment]
I'm terribly unlucky with ai.server releases :(
