### ISSUE TITLE
Error when adding repo to HA add-on store

### ISSUE THREAD

**Issue by mclever** [skrashevich/hassio-addons#3]
I get this error when trying to add the https://github.com/skrashevich/hassio-addons repo to HA add-on store

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://hub.docker.com/r/skrashevich/double-take /data/addons/git/2b339969 stderr: 'Cloning into '/data/addons/git/2b339969'... fatal: https://hub.docker.com/r/skrashevich/double-take/info/refs not valid: is this a git repository? '

Should this work?

Thanks for bringing double take back to life!

**Comment by skrashevich** [comment]
I can't reproduce this error. Are sure that you write `https://github.com/skrashevich/hassio-addons` in add-on repo adding window?

**Comment by mclever** [comment]
Yes, copy and paste. Maybe because I have the old one still installed?

**Comment by mclever** [comment]
Revisited this today and it worked. Still have the original installed so not sure why it worked this time.
