### ISSUE TITLE
Feature request: Arm64 based version of the CodeProject AI addon

### ISSUE THREAD

**Issue by Aaper** [skrashevich/hassio-addons#5]
As there is an official docker image of the CodeProject AI docker image for Arm64 architectures, it would be nice to have a version of this addon using the named image to be able to run it on a raspberry pi.

**Comment by skrashevich** [comment]
Added. But AI.Server works extremely unstable on arm64. i'll only support the x86-64 version of the ai.server add-on. any problems with arm64 versions (not directly related to repository add-on configuration) will be ignored.

**Comment by Aaper** [comment]
There seems to be something wrong with the new addons. I've got the following messages and the new addon is not showing up:

23-08-31 17:30:46 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/git/0a217ee8/ai.server.arm64/config.yaml: value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386'] @ data['arch'][0]. Got 'arm64' 
23-08-31 17:30:46 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/git/0a217ee8/ai.server.rpi64/config.yaml: value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386'] @ data['arch'][0]. Got 'arm64'
